package AppGerenciamentoVendas.View.Relatorio;

import AppGerenciamentoVendas.Model.Cliente;
import AppGerenciamentoVendas.Service.ClienteService;
import AppGerenciamentoVendas.View.Cadastro.CadastroPedidoView;

/**
 *
 * @author Luiz
 */
public class RelatorioClientesView extends javax.swing.JDialog {
    
    ClienteService clienteService = new ClienteService();
    Cliente clienteCadastro = new Cliente();
    private CadastroPedidoView cadastroPedido;
    
    public RelatorioClientesView(java.awt.Frame parent, boolean modal, CadastroPedidoView cadastroPedido) {
        super(parent, modal);
        initComponents();
        this.cadastroPedido = cadastroPedido;
        carregarClientes();
    }

        public void carregarClientes(){
            tblClientesCadastrados.setModel(clienteService.carregarTabelaCodigoENome());
            cadastroPedido.setCliente(clienteCadastro.getId(), clienteCadastro.getNome());
            this.dispose();
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientesCadastrados = new javax.swing.JTable();
        btnCarregarCliente = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblClientesCadastrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblClientesCadastrados);

        btnCarregarCliente.setText("Carregar Cliente");
        btnCarregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarClienteActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCarregarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCarregarCliente)
                    .addComponent(btnFechar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarClienteActionPerformed
        Long idCliente = (Long) tblClientesCadastrados.getModel().getValueAt(tblClientesCadastrados.getSelectedRow(), 0);
        clienteCadastro = clienteService.carregaCliente(idCliente);
        cadastroPedido.setCliente(clienteCadastro.getId(), clienteCadastro.getNome());
        this.dispose();
    }//GEN-LAST:event_btnCarregarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarregarCliente;
    private javax.swing.JButton btnFechar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblClientesCadastrados;
    // End of variables declaration//GEN-END:variables
}
