package AppGerenciamentoVendas.View.MenuPrincipal;

import AppGerenciamentoVendas.View.Cadastro.CadastroPedidoView;
import AppGerenciamentoVendas.View.Cadastro.ClientesCadastradosView;
import AppGerenciamentoVendas.View.Cadastro.ProdutosCadastradosView;
import AppGerenciamentoVendas.View.Gerenciamento.GerenciamentoPedidos;

/**
 *
 * @author Luiz
 */
public class MenuPrincipalView extends javax.swing.JDialog {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipalView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuCliente = new javax.swing.JMenuItem();
        mnuProduto = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuCadastrarPedidos = new javax.swing.JMenuItem();
        mnuConsultaPedidos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jMenu1.setText("Cadastro");

        mnuCliente.setText("Cliente");
        mnuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClienteActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCliente);

        mnuProduto.setText("Produto");
        mnuProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(mnuProduto);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Pedido de Compra");

        mnuCadastrarPedidos.setText("Cadastrar Pedido");
        mnuCadastrarPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastrarPedidosActionPerformed(evt);
            }
        });
        jMenu2.add(mnuCadastrarPedidos);

        mnuConsultaPedidos.setText("Consulta Pedidos");
        mnuConsultaPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultaPedidosActionPerformed(evt);
            }
        });
        jMenu2.add(mnuConsultaPedidos);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClienteActionPerformed
         ClientesCadastradosView clienteCadastro = new ClientesCadastradosView(null, true);
         clienteCadastro.setVisible(true);
    }//GEN-LAST:event_mnuClienteActionPerformed

    private void mnuProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProdutoActionPerformed
        ProdutosCadastradosView produtoCadastro = new ProdutosCadastradosView(null, true);
        produtoCadastro.setVisible(true);
    }//GEN-LAST:event_mnuProdutoActionPerformed

    private void mnuCadastrarPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastrarPedidosActionPerformed
        try {
        CadastroPedidoView cadastroPedido = new CadastroPedidoView(null, true);
            cadastroPedido.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_mnuCadastrarPedidosActionPerformed

    private void mnuConsultaPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultaPedidosActionPerformed
        GerenciamentoPedidos gerenciamentoPedidos = new GerenciamentoPedidos(null, true);
        gerenciamentoPedidos.setVisible(true);
    }//GEN-LAST:event_mnuConsultaPedidosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuCadastrarPedidos;
    private javax.swing.JMenuItem mnuCliente;
    private javax.swing.JMenuItem mnuConsultaPedidos;
    private javax.swing.JMenuItem mnuProduto;
    // End of variables declaration//GEN-END:variables
}
