package AppGerenciamentoVendas.View.Cadastro;

import AppGerenciamentoVendas.Model.Cliente;
import AppGerenciamentoVendas.Model.ItemPedido;
import AppGerenciamentoVendas.Model.Pedido;
import AppGerenciamentoVendas.Model.StatusPedido;
import AppGerenciamentoVendas.Service.ClienteService;
import AppGerenciamentoVendas.Service.ItemPedidoService;
import AppGerenciamentoVendas.Service.PedidoService;
import AppGerenciamentoVendas.Util.Util;
import AppGerenciamentoVendas.View.Relatorio.RelatorioClientesView;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Luiz
 */
public class CadastroPedidoView extends javax.swing.JDialog {

    private javax.swing.JTable tabelaPedido;
    private DefaultTableModel modeloTabela;
    private List<ItemPedido> itensPedido = new ArrayList<>();
    private PedidoService pedidoService = new PedidoService();
    private ItemPedidoService itemPedidoService = new ItemPedidoService();
    private ClienteService clienteService = new ClienteService();

    public CadastroPedidoView(java.awt.Frame parent, boolean modal) throws Exception {
        super(parent, modal);
        initComponents();
        inicializarTabela();
        txtDataPedido.setText(Util.getDataAtual());
    }

    private void inicializarTabela() {
        tabelaPedido = new javax.swing.JTable();
        modeloTabela = new DefaultTableModel(new Object[]{"Produto", "Quantidade", "Valor Total"}, 0);
        tabelaPedido.setModel(modeloTabela);
        JScrollPane scrollPane = new JScrollPane(tabelaPedido);
        add(scrollPane);
    }

    private void atualizarValorTotal() {
        BigDecimal valorTotal = BigDecimal.ZERO;
        for (ItemPedido item : itensPedido) {
            valorTotal = valorTotal.add(item.getValorTotal());
        }
        txtValorTotal.setText(valorTotal.toString());
    }

    private void limparCampos() {
        txtCodigoCliente.setText("");
        txtNomeCliente.setText("");
        txtValorTotal.setText("");
        modeloTabela.setRowCount(0); // Limpa a tabela de itens do pedido
        itensPedido.clear(); // Limpa a lista de itens do pedido
    }

    public void adicionarProdutoNoPedido(ItemPedido itemPedido) {
        ItemPedido itemPedidoExistente = new ItemPedido();

        if (itensPedido.isEmpty()) {
            itensPedido.add(itemPedido);
        } else {
            for (ItemPedido item : itensPedido) {
                if (item.getProduto().getId() == itemPedido.getProduto().getId()) {
                    itemPedidoExistente = item;
                    itemPedidoExistente.setQuantidade(item.getQuantidade() + itemPedido.getQuantidade());
                    itemPedidoExistente.setValorTotal(item.getValorTotal().add(itemPedido.getValorTotal()));

                    itensPedido.remove(item);
                    itensPedido.add(itemPedidoExistente);
                    carregarTabela();
                    atualizarValorTotal();
                    return;
                }
            }
            itensPedido.add(itemPedido);
        }
        carregarTabela();
        atualizarValorTotal();
    }

    public void setCliente(Long codigo, String nome) {
        txtCodigoCliente.setText(String.valueOf(codigo));
        txtNomeCliente.setText(nome);
    }

    public void carregarTabela() {
        Object[][] itens = new Object[itensPedido.size()][3];

        int i = 0;
        for (ItemPedido item : itensPedido) {

            itens[i][0] = item.getProduto().getDescricao();
            itens[i][1] = item.getQuantidade();
            itens[i][2] = item.getValorTotal();

            i++;
        }

        TableModel model = new DefaultTableModel(itens, new Object[]{"Produto", "Quantidade", "Valor Total"}) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblItensPedido.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdicionarItem = new javax.swing.JButton();
        btnExcluirItem = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItensPedido = new javax.swing.JTable();
        lblValorTotal = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JTextField();
        txtNomeCliente = new javax.swing.JTextField();
        txtCodigoCliente = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblCodigoCliente = new javax.swing.JLabel();
        lblNomeCliente = new javax.swing.JLabel();
        btnAdicionarCliente = new javax.swing.JButton();
        txtDataPedido = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(null);

        btnAdicionarItem.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAdicionarItem.setText("Adicionar Item");
        btnAdicionarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarItemActionPerformed(evt);
            }
        });

        btnExcluirItem.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnExcluirItem.setText("Excluir Item");
        btnExcluirItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirItemActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnFechar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnFechar.setText("Fechar");

        tblItensPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblItensPedido);

        lblValorTotal.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblValorTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValorTotal.setText("Valor Total");

        txtValorTotal.setEditable(false);

        txtNomeCliente.setEditable(false);
        txtNomeCliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        txtCodigoCliente.setEditable(false);
        txtCodigoCliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        lblCodigoCliente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCodigoCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCodigoCliente.setText("Codigo Cliente");

        lblNomeCliente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblNomeCliente.setText("Nome Cliente");

        btnAdicionarCliente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAdicionarCliente.setText("Adicionar Cliente");
        btnAdicionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarClienteActionPerformed(evt);
            }
        });

        txtDataPedido.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtDataPedido.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblValorTotal)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSalvar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnFechar))
                                    .addComponent(txtValorTotal)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAdicionarItem, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                    .addComponent(btnExcluirItem, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                    .addComponent(txtDataPedido))
                                .addGap(19, 19, 19))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCodigoCliente)
                    .addComponent(txtCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNomeCliente)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdicionarCliente)
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoCliente)
                    .addComponent(lblNomeCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 14, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(btnAdicionarItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluirItem)
                        .addGap(188, 188, 188)
                        .addComponent(lblValorTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnFechar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarItemActionPerformed
        CadastroProdutoNoPedidoView cadastroProdutoNoPedido = new CadastroProdutoNoPedidoView(null, true, this);
        cadastroProdutoNoPedido.setVisible(true);

    }//GEN-LAST:event_btnAdicionarItemActionPerformed

    private void btnAdicionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarClienteActionPerformed
        RelatorioClientesView relatorioCliente = new RelatorioClientesView(null, true, this);
        relatorioCliente.setVisible(true);

    }//GEN-LAST:event_btnAdicionarClienteActionPerformed

    private void btnExcluirItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirItemActionPerformed
        int itemSelecionado = tblItensPedido.getSelectedRow();
        try {
            itensPedido.remove(itemSelecionado);
            JOptionPane.showMessageDialog(this, "Produto excluido com Sucesso", "SUCESS", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Selecione um item", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        carregarTabela();
        atualizarValorTotal();
    }//GEN-LAST:event_btnExcluirItemActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        //1 - Criar o comando que salva o pedido com as seguintes informações: id, data, valortotal, status.
        Pedido pedido = new Pedido();

        pedido.setCliente(new Cliente(Long.valueOf(txtCodigoCliente.getText())));
        pedido.setData(LocalDate.parse(txtDataPedido.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        pedido.setValorTotal(new BigDecimal(txtValorTotal.getText()));
        pedido.setStatusPedido(StatusPedido.ATIVO);

        try {
            BigDecimal limiteDisponivel = clienteService.verificarLimiteCompra(Long.valueOf(txtCodigoCliente.getText()), new BigDecimal(txtValorTotal.getText()));

            if (limiteDisponivel.compareTo(new BigDecimal(txtValorTotal.getText())) < 0) {
                JOptionPane.showMessageDialog(this, "Limite Excedido. Valor disponivel para compra: " + limiteDisponivel, "ERRO", JOptionPane.ERROR_MESSAGE);
            } else {
                //2 - Criar o comando que salva os itensPedido com as seguintes informações: 
                pedidoService.salvarPedido(pedido);

                pedido.setId(pedidoService.carregarId());

                for (ItemPedido itemPedido : itensPedido) {
                    itemPedido.setPedido(pedido);
                }

                itemPedidoService.adicionarItensPedido(itensPedido);
                
                BigDecimal limiteDisponivelaAtualizado = clienteService.verificarLimiteCompra(Long.valueOf(txtCodigoCliente.getText()), new BigDecimal(txtValorTotal.getText()));
               
                JOptionPane.showMessageDialog(this, "Pedido confirmado com sucesso! Valor disponivel para as próximas compras: " + limiteDisponivelaAtualizado, "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
                limparCampos();
                carregarTabela();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao confirmar pedido: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarCliente;
    private javax.swing.JButton btnAdicionarItem;
    private javax.swing.JButton btnExcluirItem;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCodigoCliente;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JTable tblItensPedido;
    private javax.swing.JTextField txtCodigoCliente;
    private javax.swing.JTextField txtDataPedido;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables

}
