package AppGerenciamentoVendas.View.Cadastro;

import AppGerenciamentoVendas.Model.ItemPedido;
import AppGerenciamentoVendas.Model.Produto;
import AppGerenciamentoVendas.Service.ProdutoService;
import AppGerenciamentoVendas.View.Cadastro.CadastroPedidoView;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Luiz
 */
public class CadastroProdutoNoPedidoView extends javax.swing.JDialog {

    private ProdutoService produtoService = new ProdutoService();
    private ItemPedido itemPedido = new ItemPedido();
    private CadastroPedidoView cadastroPedidoView;
    private BigDecimal valorTotal = new BigDecimal(0);

    public CadastroProdutoNoPedidoView(java.awt.Frame parent, boolean modal, CadastroPedidoView cadastroPedidoView) {
        super(parent, modal);
        this.cadastroPedidoView = cadastroPedidoView;
        initComponents();
        carregarComboBoxProduto();
    }

    private void carregarComboBoxProduto() {
        List<Produto> produtos = produtoService.carregarListaProdutos();
        Object[] valoresModelProduto = new Object[produtos.size()];
        int i = 0;
        for (Produto produto : produtos) {
            valoresModelProduto[i] = produto;
            i++;
        }
        DefaultComboBoxModel modelProdutos = new DefaultComboBoxModel(valoresModelProduto);
        cboProduto.setModel(modelProdutos);
    }

    public void setValorTotal() {
        Produto produtoSelecionado = (Produto) cboProduto.getSelectedItem();

        if (produtoSelecionado != null) {
            try {
                int quantidade = Integer.parseInt(txtQtdeProduto.getText());
                valorTotal = produtoSelecionado.getPreco().multiply(BigDecimal.valueOf(quantidade));
                txtValorTotal.setText(valorTotal.toString());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Insira uma quantidade válida!", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        btnCarregarProduto = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        lblProduto = new javax.swing.JLabel();
        lblQuantidade = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();
        cboProduto = new javax.swing.JComboBox<>();
        txtQtdeProduto = new javax.swing.JTextField();
        txtValorTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnCarregarProduto.setText("Carregar");
        btnCarregarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarProdutoActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        lblProduto.setText("Produto");

        lblQuantidade.setText("Quantidade");

        lblValorTotal.setText("Valor Total");

        txtQtdeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtdeProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 93, Short.MAX_VALUE)
                        .addComponent(btnCarregarProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblProduto)
                            .addComponent(lblQuantidade)
                            .addComponent(lblValorTotal)
                            .addComponent(cboProduto, 0, 146, Short.MAX_VALUE)
                            .addComponent(txtQtdeProduto)
                            .addComponent(txtValorTotal))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(lblQuantidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQtdeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(lblValorTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCarregarProduto)
                    .addComponent(btnFechar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarregarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarProdutoActionPerformed
        Produto produtoSelecionado = (Produto) cboProduto.getSelectedItem();
        Integer quantidade = Integer.parseInt(txtQtdeProduto.getText());
        
        itemPedido.setProduto(produtoSelecionado);
        itemPedido.setQuantidade(quantidade);
        itemPedido.setValorTotal(valorTotal);
        
        try {
        cadastroPedidoView.adicionarProdutoNoPedido(itemPedido);
            
        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, "Por favor, insira uma quantidade válida.", "Erro", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
        this.dispose();
    }//GEN-LAST:event_btnCarregarProdutoActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void txtQtdeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtdeProdutoActionPerformed
        setValorTotal();
    }//GEN-LAST:event_txtQtdeProdutoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarregarProduto;
    private javax.swing.JButton btnFechar;
    private javax.swing.JComboBox<String> cboProduto;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JTextField txtQtdeProduto;
    private javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables
}
