package AppGerenciamentoVendas.View.Cadastro;

import AppGerenciamentoVendas.Model.Produto;
import AppGerenciamentoVendas.Service.ProdutoService;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ProdutosCadastradosView extends javax.swing.JDialog {

    ProdutoService produtoService = new ProdutoService();
    private List<Produto> listaProduto = new ArrayList<>();

    public ProdutosCadastradosView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        carregarTabelaCadastro();
    }

    public void carregarTabelaCadastro() {
        listaProduto = produtoService.carregarListaProdutos();

        Object[][] produtos = new Object[listaProduto.size()][Produto.class.getDeclaredFields().length];

        int i = 0;
        for (Produto produto : listaProduto) {
            produtos[i][0] = produto.getId();
            produtos[i][1] = produto.getDescricao();
            produtos[i][2] = produto.getPreco();
            i++;
        }
        DefaultTableModel dataModel = new DefaultTableModel(produtos, new Object[]{"Codigo", "Descricao", "Preco"}) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblProdutosCadastrados.setModel(dataModel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdutosCadastrados = new javax.swing.JTable();
        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblProdutosCadastrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblProdutosCadastrados);

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFechar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir)
                    .addComponent(btnFechar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        CadastroProdutoView cadastroProduto = new CadastroProdutoView(null, true, null);
        cadastroProduto.setVisible(true);
        carregarTabelaCadastro();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        if (tblProdutosCadastrados.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um cliente para editar", "ERRO", JOptionPane.WARNING_MESSAGE);
        } else {
            Long idProduto = (Long) tblProdutosCadastrados.getModel().getValueAt(tblProdutosCadastrados.getSelectedRow(), 0);
            CadastroProdutoView cadastroProduto = new CadastroProdutoView(null, true, idProduto);
            cadastroProduto.setVisible(true);
            carregarTabelaCadastro();
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        if (tblProdutosCadastrados.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um cliente para excluir", "ERRO", JOptionPane.WARNING_MESSAGE);
        } else {
            Long id = (Long) tblProdutosCadastrados.getModel().getValueAt(tblProdutosCadastrados.getSelectedRow(), 0);
            try {
                produtoService.excluirProduto(id);
            } catch (Exception ex) {
            }
            JOptionPane.showMessageDialog(this, "Produto excluido com Sucesso", "SUCESS", JOptionPane.INFORMATION_MESSAGE);
        }

        carregarTabelaCadastro();

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProdutosCadastrados;
    // End of variables declaration//GEN-END:variables
}
