package AppGerenciamentoVendas.View.Gerenciamento;

import AppGerenciamentoVendas.Model.Cliente;
import AppGerenciamentoVendas.Service.PedidoService;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luiz
 */
public class GerenciamentoPedidos extends javax.swing.JDialog {

    private javax.swing.JTable jTablePedido;
    private DefaultTableModel modeloTabela;
    public PedidoService pedidoService = new PedidoService();
    private List<Cliente> itensPedido = new ArrayList<>();
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

    public GerenciamentoPedidos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //itemSelecionadoTeste();
    }

    private void carregarDados() throws Exception {
        String situacao = cboSituacao.getSelectedItem().toString();
        String consultaPor = cboTipoConsulta.getSelectedItem().toString();
        String dataInicioStr = txtDataInicio.getText();
        String dataFimStr = txtDataFim.getText();
        String idClienteString = txtCodCliente.getText();
        String idProdutoString = txtCodProduto.getText();
        LocalDate dataInicio = null;
        LocalDate dataFim = null;
        Long idCliente = null;
        Long idProduto = null;

        if (!dataInicioStr.isEmpty()) {
            dataInicio = LocalDate.parse(dataInicioStr, formatter);
        }
        if (!dataFimStr.isEmpty()) {
            dataFim = LocalDate.parse(dataFimStr, formatter);
        }

        if (!idClienteString.isEmpty()) {
            idCliente = Long.parseLong(idClienteString);
        }
        if (!idProdutoString.isEmpty()) {
            idProduto = Long.parseLong(idProdutoString);
        }

        validacaoCamposDatas(dataInicio, dataFim);

        if (consultaPor.equals("CLIENTE")) {
            DefaultTableModel modeloTabela = new DefaultTableModel(new Object[]{"CODIGO", "NOME", "VALOR TOTAL"}, 0);
            tblDadosPedidos.setModel(modeloTabela);

            List<Object[]> clientes = pedidoService.consultaPedidosVisualizacaoPorCliente(situacao, dataInicio, dataFim, idCliente, idProduto);

            for (Object[] cliente : clientes) {
                modeloTabela.addRow(cliente);
            }

        } else if (consultaPor.equals("PRODUTO")) {
            DefaultTableModel modeloTabela = new DefaultTableModel(new Object[]{"CODIGO", "DESCRICAO DO PRODUTO", "VALOR TOTAL"}, 0);
            tblDadosPedidos.setModel(modeloTabela);
            List<Object[]> produtos = pedidoService.consultaPedidosVisualizacaoPorProduto(situacao, dataInicio, dataFim, idCliente, idProduto);
            for (Object[] produto : produtos) {
                modeloTabela.addRow(produto);
            }
        }
    }

    public void validacaoCamposDatas(LocalDate dataInicio, LocalDate dataFim) {

        if (dataInicio == null && dataFim == null) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha o período para realizar a consulta.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (dataInicio == null && dataFim != null) {
            JOptionPane.showMessageDialog(this, "Por favor, insira a data inicial.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (dataInicio != null && dataFim == null) {
            JOptionPane.showMessageDialog(this, "Por favor, insira a data final.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (dataInicio != null && dataFim != null) {
            if (dataInicio.isAfter(dataFim)) {
                JOptionPane.showMessageDialog(this, "A data de início deve ser menor ou igual à data de fim.",
                        "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDadosPedidos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        cboTipoConsulta = new javax.swing.JComboBox<>();
        txtDataInicio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtDataFim = new javax.swing.JTextField();
        cboSituacao = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnCarregar = new javax.swing.JButton();
        txtCodCliente = new javax.swing.JTextField();
        lblCodCliente = new javax.swing.JLabel();
        txtCodProduto = new javax.swing.JTextField();
        lblCodProduto = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblDadosPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblDadosPedidos);

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("Fechar");

        cboTipoConsulta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cboTipoConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CLIENTE", "PRODUTO" }));

        txtDataInicio.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("à");

        txtDataFim.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        cboSituacao.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cboSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ATIVO", "EXCLUIDO" }));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Consulta");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Status Pedido");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Período");

        btnCarregar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCarregar.setText("Carregar");
        btnCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarActionPerformed(evt);
            }
        });

        txtCodCliente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        lblCodCliente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCodCliente.setText("Cod Cliente");

        txtCodProduto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        lblCodProduto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCodProduto.setText("Cod Produto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(cboTipoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cboSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCodCliente)
                                .addComponent(txtCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblCodProduto)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                                    .addComponent(btnCarregar))))
                        .addComponent(jScrollPane1)
                        .addComponent(jSeparator3)
                        .addComponent(jSeparator2)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblCodCliente)
                            .addComponent(lblCodProduto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(txtDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarregar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboTipoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(8, 8, 8)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarActionPerformed
        try {
            carregarDados();
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_btnCarregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarregar;
    private javax.swing.JComboBox<String> cboSituacao;
    private javax.swing.JComboBox<String> cboTipoConsulta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblCodCliente;
    private javax.swing.JLabel lblCodProduto;
    private javax.swing.JTable tblDadosPedidos;
    private javax.swing.JTextField txtCodCliente;
    private javax.swing.JTextField txtCodProduto;
    private javax.swing.JTextField txtDataFim;
    private javax.swing.JTextField txtDataInicio;
    // End of variables declaration//GEN-END:variables
}
